# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='fullName',
        ),
        migrations.AddField(
            model_name='student',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='firstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
